### ISSUE TITLE
Error when building documentation

### ISSUE THREAD

**Issue by AbelHutten** [JuliaDynamics/ConcurrentSim.jl#102]
When I try to build the documentation locally, I get the following error:

```
$ julia make.jl
ERROR: LoadError: ArgumentError: makedocs() got passed invalid keyword arguments:
strict = true
Stacktrace:
[...]
```

If I go into make.jl and remove the "strict = true" line, the documentation builds as expected.

If this is not a problem with the code but instead a problem with how I tried to use it, then I apologize.

I am completely new to collaborating on github, and any feedback would be greatly appreciated.

**Comment by Krastanov** [comment]
This indeed needs to be fixed. It is due to Documenter v1 being released a few weeks ago, which made a few minor breaking changes in how docs are to be built. We indeed need to drop `strict=true` but also potentially add `warnonly=...` as appropriate to make sure documentation issues get flagged by CI.

**Comment by Krastanov** [comment]
It is now fixed. Thank you for reporting this!
