### ISSUE TITLE
port SimJulia.jl 'school' example and add description of that to the docs

### ISSUE THREAD

**Issue by asmirnov69** [JuliaDynamics/ConcurrentSim.jl#106]
This example would be particular useful to have in ConcurrentSim.jl documentation: [school](https://simjuliajl.readthedocs.io/en/stable/topical_guides/3_events.html#example-usages-for-event)

---
I start using ConcurrentSim.jl as part of my implementation of Julia-based discrete simulation project. Since it is first time I am doing such kind of code I am frequently using more friendly docs from SimJulia.jl project: https://simjuliajl.readthedocs.io/en/stable/welcome.html

I'd like to suggest to add more documentation into ConcurrentSim.jl to 'Topical Guides/Events' section of documentation. At glance it looks like the task of taking old SimJulia.jl docstring and put it into ConcurrentSim.jl, making sure that example code is actually works.

**Comment by Krastanov** [comment]
Hi, asmirnov69! You are right, but there are a few issues: The old docs you are looking at are for a very old version of SimJulia, long before SimJulia was renamed to ConcurrentSim. These docs were discarded due to changes that were made to SimJulia before any name changes. They were discarded because internal changes in SimJulia made them incorrect. ConcurrentSim did not delete any docs that were available at the time of transition.

Thus, some of the examples you are relying on might be randomly incorrect (some of them will still be fine). The original developer did not have the bandwidth to translate all examples.

**Most importantly though, I completely agree with you that we need more docs**. We are a bit short staffed though, so it would not happen in the next few months. If you would like to help this open source project, I would be eager to help you contribute documentation and examples.

**Comment by asmirnov69** [comment]
yes, i will try to contribute docs and examples. to move ahead with this particular issue and possibly more. I want concentrate on [school](https://simjuliajl.readthedocs.io/en/stable/topical_guides/3_events.html#example-usages-for-event) example since that is very close to what I am doing right now.

**Comment by Krastanov** [comment]
wonderful! That would be greatly appreciated
